### ISSUE TITLE
Export broken in latest versions of Etherpad

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ep_markdown#28]
```
[2020-03-15 13:16:14.871] [ERROR] console - (node:4584) UnhandledPromiseRejectionWarning: apierror: text is not a string
    at Object.exports.getPad (/home/jose/etherpad-lite/src/node/db/PadManager.js:126:13)
    at Object.exports.getPadMarkdownDocument (/home/jose/etherpad-lite/node_modules/ep_markdown/exportMarkdown.js:426:14)
    at /home/jose/etherpad-lite/node_modules/ep_markdown/express.js:8:20
    at Layer.handle [as handle_request] (/home/jose/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/jose/etherpad-lite/src/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/jose/etherpad-lite/src/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/jose/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
    at /home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:281:22
    at param (/home/jose/etherpad-lite/src/node_modules/express/lib/router/index.js:354:14)
[2020-03-15 13:16:14.875] [ERROR] console - (node:4584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[2020-03-15 13:16:14.875] [ERROR] console - (node:4584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by JohnMcLear** [comment]
fixed
