### ISSUE TITLE
Error when trying to export as markdown

### ISSUE THREAD

**Issue by meaz** [ether/ep_markdown#31]
I'm trying to install this plugin. It seems to work, but I have an error when I try to export to markdown.

Here is what I get in this log:

```
Apr 17 04:33:43 debian10 run.sh[17102]: #033[31m[2020-04-17 04:33:43.262] [ERROR] console - #033[39m(node:17102) UnhandledPromiseRejectionWarning: TypeError: callback is not a function
Apr 17 04:33:43 debian10 run.sh[17102]:     at Object.exports.getPad (/var/www/etherpad-lite/src/node/db/PadManager.js:161:5)
Apr 17 04:33:43 debian10 run.sh[17102]:     at Object.exports.getPadMarkdownDocument (/var/www/etherpad-lite/node_modules/ep_markdown/exportMarkdown.js:422:30)
Apr 17 04:33:43 debian10 run.sh[17102]:     at /var/www/etherpad-lite/node_modules/ep_markdown/express.js:8:20
Apr 17 04:33:43 debian10 run.sh[17102]:     at Layer.handle [as handle_request] (/var/www/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
Apr 17 04:33:43 debian10 run.sh[17102]:     at next (/var/www/etherpad-lite/src/node_modules/express/lib/router/route.js:137:13)
Apr 17 04:33:43 debian10 run.sh[17102]:     at Route.dispatch (/var/www/etherpad-lite/src/node_modules/express/lib/router/route.js:112:3)
Apr 17 04:33:43 debian10 run.sh[17102]:     at Layer.handle [as handle_request] (/var/www/etherpad-lite/src/node_modules/express/lib/router/layer.js:95:5)
Apr 17 04:33:43 debian10 run.sh[17102]:     at /var/www/etherpad-lite/src/node_modules/express/lib/router/index.js:281:22
Apr 17 04:33:43 debian10 run.sh[17102]:     at param (/var/www/etherpad-lite/src/node_modules/express/lib/router/index.js:354:14)
Apr 17 04:33:43 debian10 run.sh[17102]:     at param (/var/www/etherpad-lite/src/node_modules/express/lib/router/index.js:365:14)
Apr 17 04:33:43 debian10 run.sh[17102]:     at paramCallback (/var/www/etherpad-lite/src/node_modules/express/lib/router/index.js:401:21)
Apr 17 04:33:43 debian10 run.sh[17102]:     at /var/www/etherpad-lite/src/node/hooks/express/padurlsanitize.js:28:9
Apr 17 04:33:43 debian10 run.sh[17102]:     at /var/www/etherpad-lite/src/node/db/PadManager.js:216:7
Apr 17 04:33:43 debian10 run.sh[17102]:     at Object.callback (/var/www/etherpad-lite/src/node/db/PadManager.js:192:7)
Apr 17 04:33:43 debian10 run.sh[17102]:     at /var/www/etherpad-lite/src/node_modules/ueberdb2/CloneAndAtomicLayer.js:100:17
Apr 17 04:33:43 debian10 run.sh[17102]:     at exports.database.get (/var/www/etherpad-lite/src/node_modules/ueberdb2/CacheAndBufferLayer.js:144:5)
Apr 17 04:33:43 debian10 run.sh[17102]: #033[31m[2020-04-17 04:33:43.262] [ERROR] console - #033[39m(node:17102) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```
I use etherpad-lite 1.7.5

**Comment by meaz** [comment]
But only 1.8.0 version is available...

**Comment by JohnMcLear** [comment]
<3
